"""Regenerate the self-contained KernelBench entry point after editing C++/CUDA."""
from pathlib import Path

root = Path(__file__).resolve().parent
header = '''"""Self-contained direct register-reuse stencil; generated by generate_model.py."""
import functools
import hashlib
import os
import tempfile
from pathlib import Path

import torch
from torch.utils.cpp_extension import load

'''
loader = '''

@functools.lru_cache(maxsize=1)
def _get_extension():
    rows = int(os.environ.get("STENCIL_DIRECT_V7_ROWS", "8"))
    if rows not in (8, 16):
        raise ValueError("STENCIL_DIRECT_V7_ROWS must be 8 or 16")
    digest = hashlib.sha256((_CPP_SOURCE + _CUDA_SOURCE + str(rows)).encode()).hexdigest()[:16]
    directory = Path(tempfile.gettempdir()) / ("stencil_direct_v7_" + digest)
    directory.mkdir(parents=True, exist_ok=True)
    # Atomically publish sources; concurrent evaluation processes may import
    # this same source. PyTorch's extension loader serializes the build itself.
    for filename, source in (("binding.cpp", _CPP_SOURCE), ("kernel.cu", _CUDA_SOURCE)):
        target = directory / filename
        if not target.exists() or target.read_text() != source:
            temporary = directory / (filename + "." + str(os.getpid()) + ".tmp")
            temporary.write_text(source)
            temporary.replace(target)
    return load(
        name="stencil_direct_v7_" + digest,
        sources=[str(directory / "binding.cpp"), str(directory / "kernel.cu")],
        build_directory=str(directory),
        extra_cflags=["-O3"],
        extra_cuda_cflags=["-O3", "-lineinfo", f"-DSTENCIL_ROWS={rows}"],
        verbose=False,
    )


class ModelNew(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(1, 1, kernel_size=7, stride=1, padding=3)

    def forward(self, x):
        if not x.is_cuda:
            raise ValueError("ModelNew requires a CUDA input")
        if x.ndim not in (3, 4) or x.shape[-3] != 1:
            raise ValueError("Expected (N,1,H,W) or (1,H,W) input")
        if x.shape[-2] == 0 or x.shape[-1] == 0:
            raise ValueError("Spatial dimensions must be nonempty")
        return _get_extension().forward(x, self.conv1.weight, self.conv1.bias)


def get_inputs():
    return [torch.rand(1, 1, 10240, 10240)]


def get_init_inputs():
    return []
'''
(root / 'model.py').write_text(
    header
    + '_CPP_SOURCE = r"""' + chr(10) + (root / 'stencil_cuda.cpp').read_text() + '"""' + chr(10) * 2
    + '_CUDA_SOURCE = r"""' + chr(10) + (root / 'stencil_cuda_kernel.cu').read_text() + '"""'
    + loader
)
