"""Regenerate the self-contained KernelBench entry point after editing C++/CUDA."""
from pathlib import Path

root = Path(__file__).resolve().parent
header = '''"""Self-contained shared-input Tensor Core stencil; generated by generate_model.py."""
import functools
import hashlib
import os
import tempfile
from pathlib import Path

import torch
from torch.utils.cpp_extension import load

'''
loader = '''

@functools.lru_cache(maxsize=1)
def _get_extension():
    digest = hashlib.sha256((_CPP_SOURCE + _CUDA_SOURCE).encode()).hexdigest()[:16]
    directory = Path(tempfile.gettempdir()) / ("stencil_shared_mma_" + digest)
    directory.mkdir(parents=True, exist_ok=True)
    # Atomically publish sources; concurrent evaluation processes may import
    # this same source. PyTorch's extension loader serializes the build itself.
    for filename, source in (("binding.cpp", _CPP_SOURCE), ("kernel.cu", _CUDA_SOURCE)):
        target = directory / filename
        if not target.exists() or target.read_text() != source:
            temporary = directory / (filename + "." + str(os.getpid()) + ".tmp")
            temporary.write_text(source)
            temporary.replace(target)
    return load(
        name="stencil_shared_mma_" + digest,
        sources=[str(directory / "binding.cpp"), str(directory / "kernel.cu")],
        build_directory=str(directory),
        extra_cflags=["-O3"],
        extra_cuda_cflags=["-O3", "-lineinfo"],
        verbose=False,
    )


class ModelNew(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1_weight = torch.nn.Parameter(torch.empty(1, 1, 7, 7))
        self.conv1_bias = torch.nn.Parameter(torch.empty(1))
        torch.nn.init.kaiming_uniform_(self.conv1_weight, a=5 ** 0.5)
        fan_in, _ = torch.nn.init._calculate_fan_in_and_fan_out(self.conv1_weight)
        bound = 1 / fan_in ** 0.5 if fan_in > 0 else 0
        torch.nn.init.uniform_(self.conv1_bias, -bound, bound)

    def forward(self, x):
        return _get_extension().forward(x, self.conv1_weight, self.conv1_bias)


def get_inputs():
    return [torch.rand(1, 1, 10240, 10240)]


def get_init_inputs():
    return []
'''
(root / 'model.py').write_text(
    header
    + '_CPP_SOURCE = r"""' + chr(10) + (root / 'stencil_cuda.cpp').read_text() + '"""' + chr(10) * 2
    + '_CUDA_SOURCE = r"""' + chr(10) + (root / 'stencil_cuda_kernel.cu').read_text() + '"""'
    + loader
)
