"""Self-contained shared-input Tensor Core stencil; generated by generate_model.py."""
import functools
import hashlib
import os
import tempfile
from pathlib import Path

import torch
from torch.utils.cpp_extension import load

_CPP_SOURCE = r"""
#include <torch/extension.h>
#include <ATen/cuda/CUDAContext.h>
#include <c10/cuda/CUDAGuard.h>
#include <c10/cuda/CUDAException.h>
#include <limits>

void launch_stencil(const void*, const void*, const void*, void*,
                    int, int, int, bool, cudaStream_t);

torch::Tensor stencil_forward(torch::Tensor x, torch::Tensor w, torch::Tensor b) {
  TORCH_CHECK(x.is_cuda() && w.is_cuda() && b.is_cuda(), "all tensors must be CUDA");
  TORCH_CHECK(x.dim() == 4 && x.size(1) == 1, "expected [N,1,H,W]");
  TORCH_CHECK(w.numel() == 49 && b.numel() == 1, "expected 7x7 weight and scalar bias");
  TORCH_CHECK(x.device() == w.device() && x.device() == b.device(), "device mismatch");
  TORCH_CHECK(x.scalar_type() == w.scalar_type() && x.scalar_type() == b.scalar_type(), "dtype mismatch");
  TORCH_CHECK(x.scalar_type() == torch::kFloat16 || x.scalar_type() == torch::kFloat32,
              "supported dtypes: float16, float32");
  TORCH_CHECK(x.size(0) <= 65535 && x.size(2) <= std::numeric_limits<int>::max() - 16 &&
              x.size(3) <= std::numeric_limits<int>::max() - 512, "shape too large");
  c10::cuda::CUDAGuard guard(x.device());
  if (x.scalar_type() == torch::kFloat16) {
    const auto* prop = at::cuda::getCurrentDeviceProperties();
    TORCH_CHECK(prop->major >= 8, "FP16 Tensor Core path requires SM80+");
  }
  x = x.contiguous(); w = w.contiguous(); b = b.contiguous();
  auto y = torch::empty_like(x);
  if (!x.numel()) return y;
  launch_stencil(x.data_ptr(), w.data_ptr(), b.data_ptr(), y.data_ptr(),
                 static_cast<int>(x.size(0)), static_cast<int>(x.size(2)),
                 static_cast<int>(x.size(3)), x.scalar_type() == torch::kFloat16,
                 at::cuda::getCurrentCUDAStream());
  C10_CUDA_KERNEL_LAUNCH_CHECK();
  return y;
}
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("forward", &stencil_forward, "Shared-input Tensor Core 7x7 stencil");
}
"""

_CUDA_SOURCE = r"""
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <stdint.h>

namespace {
// Four warps, each computing 16 horizontal 2x4 groups, for four row pairs.
constexpr int WARPS = 4;
constexpr int GROUPS = WARPS * 16;
constexpr int OUT_W = GROUPS * 4;
constexpr int OUT_H = 8;
constexpr int ROW_PAIRS = OUT_H / 2;
constexpr int UNION_H = OUT_H + 6;
constexpr int UNION_W = OUT_W + 6;
// Logical column 3 is the first aligned global vector. Shift it to
// shared column 8 so both sides of cp.async are 16-byte aligned.
constexpr int SHIFT = 5;
constexpr int PITCH = ((UNION_W + SHIFT + 15) / 16) * 16;

__device__ __forceinline__ void copy_async_16(__half* dst, const __half* src) {
#if __CUDA_ARCH__ >= 800
  unsigned address = static_cast<unsigned>(__cvta_generic_to_shared(dst));
  asm volatile("cp.async.ca.shared.global [%0], [%1], 16;" ::
               "r"(address), "l"(src) : "memory");
#else
  *reinterpret_cast<uint4*>(dst) = *reinterpret_cast<const uint4*>(src);
#endif
}

__device__ __forceinline__ void commit_async() {
#if __CUDA_ARCH__ >= 800
  asm volatile("cp.async.commit_group;" ::: "memory");
#endif
}

__device__ __forceinline__ void wait_async() {
#if __CUDA_ARCH__ >= 800
  asm volatile("cp.async.wait_group 0;" ::: "memory");
#endif
}

template<bool INTERIOR>
__device__ __forceinline__ void load_union(__half* tile, const __half* x,
                                          int64_t base, int bx, int by,
                                          int h, int w) {
  constexpr int VECTORS = OUT_W / 8;
  for (int task = threadIdx.x; task < UNION_H * VECTORS; task += WARPS * 32) {
    const int sy = task / VECTORS;
    const int sx = 3 + (task % VECTORS) * 8;
    const int iy = by + sy - 3, ix = bx + sx - 3;
    const int64_t offset = base + int64_t(iy) * w + ix;
    __half* dst = tile + sy * PITCH + sx + SHIFT;
    if (INTERIOR || (iy >= 0 && iy < h && ix >= 0 && ix + 7 < w &&
                     ((reinterpret_cast<uintptr_t>(x) + offset * sizeof(__half)) & 15) == 0)) {
      copy_async_16(dst, x + offset);
    } else {
#pragma unroll
      for (int j = 0; j < 8; ++j)
        dst[j] = (iy >= 0 && iy < h && ix + j >= 0 && ix + j < w)
                   ? x[base + int64_t(iy) * w + ix + j] : __float2half_rn(0.0f);
    }
  }
  // Only six halo values per row need scalar loads; the 256 middle values
  // use 32 aligned copies. No lane writes an async destination twice.
  for (int task = threadIdx.x; task < UNION_H * 6; task += WARPS * 32) {
    const int sy = task / 6, item = task % 6;
    const int sx = item < 3 ? item : OUT_W + item;
    const int iy = by + sy - 3, ix = bx + sx - 3;
    tile[sy * PITCH + sx + SHIFT] =
        (INTERIOR || (iy >= 0 && iy < h && ix >= 0 && ix < w))
          ? x[base + int64_t(iy) * w + ix] : __float2half_rn(0.0f);
  }
  commit_async();
}

__device__ __forceinline__ unsigned pack(__half a, __half b) {
  return unsigned(__half_as_ushort(a)) | (unsigned(__half_as_ushort(b)) << 16);
}

__device__ __forceinline__ unsigned input_pair(const __half* tile,
                                               int group, int row_pair, int k) {
  const int c = group * 4 + SHIFT;
  // Consecutive K elements can cross the ten-column window boundary.
  return pack(tile[(row_pair * 2 + k / 10) * PITCH + c + k % 10],
              tile[(row_pair * 2 + (k + 1) / 10) * PITCH + c + (k + 1) % 10]);
}

__device__ __forceinline__ void mma(float* d, unsigned a0, unsigned a1,
                                    unsigned a2, unsigned a3,
                                    unsigned b0, unsigned b1) {
#if __CUDA_ARCH__ >= 800
  asm volatile(
      "mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32 "
      "{%0,%1,%2,%3}, {%4,%5,%6,%7}, {%8,%9}, {%0,%1,%2,%3};\n"
      : "+f"(d[0]), "+f"(d[1]), "+f"(d[2]), "+f"(d[3])
      : "r"(a0), "r"(a1), "r"(a2), "r"(a3), "r"(b0), "r"(b1));
#endif
}

__device__ __forceinline__ void store_pair(__half* y, int64_t batch_base,
                                          int h, int w, int row, int col,
                                          float d0, float d1, __half bias) {
  if (row < h && col < w) {
    // Same cast-before-bias convention as the Triton candidates.
    const int64_t offset = batch_base + int64_t(row) * w + col;
    const __half lo = __hadd(__float2half_rn(d0), bias);
    const __half hi = __hadd(__float2half_rn(d1), bias);
    if (col + 1 < w && (reinterpret_cast<uintptr_t>(y + offset) & 3) == 0)
      *reinterpret_cast<__half2*>(y + offset) = __halves2half2(lo, hi);
    else {
      y[offset] = lo;
      if (col + 1 < w) y[offset + 1] = hi;
    }
  }
}

template<bool INTERIOR>
__global__ void stencil_tensorcore(const __half* __restrict__ x,
                                    const __half* __restrict__ weight,
                                    const __half* __restrict__ bias,
                                    __half* __restrict__ y, int h, int w) {
  __shared__ __align__(32) __half tile[UNION_H * PITCH];
  __shared__ __align__(32) __half weights[8 * 80];
  const int tid = threadIdx.x;
  const int lane = tid & 31;
  const int warp = tid >> 5;
  const int bx = blockIdx.x * OUT_W;
  const int by = blockIdx.y * OUT_H;
  const int64_t batch_base = int64_t(blockIdx.z) * h * w;
  const bool interior = bx >= 3 && bx + OUT_W + 3 <= w &&
                        by >= 3 && by + OUT_H + 3 <= h && (w & 7) == 0 &&
                        (reinterpret_cast<uintptr_t>(x + batch_base) & 15) == 0;
  if (interior) load_union<true>(tile, x, batch_base, bx, by, h, w);
  else load_union<false>(tile, x, batch_base, bx, by, h, w);
  // Rebuild from live parameters so .to(), load_state_dict and weight updates
  // cannot leave a stale packed weight. Reused across all warps and row pairs.
  for (int i = tid; i < 8 * 80; i += WARPS * 32) {
    const int m = i / 80, k = i % 80;
    const int ky = k / 10 - m / 4, kx = k % 10 - m % 4;
    weights[i] = (ky >= 0 && ky < 7 && kx >= 0 && kx < 7)
                   ? weight[ky * 7 + kx] : __float2half_rn(0.0f);
  }
  // Weight preparation overlaps the outstanding input copies.
  wait_async();
  __syncthreads();
  const int g = lane >> 2;
  const int t = lane & 3;
  const int group0 = warp * 16 + g;
  const int group1 = group0 + 8;
  float accum[ROW_PAIRS][4] = {};
#pragma unroll
  for (int kb = 0; kb < 80; kb += 16) {
    const int k = kb + 2 * t;
    const unsigned b0 = pack(weights[g * 80 + k], weights[g * 80 + k + 1]);
    const unsigned b1 = pack(weights[g * 80 + k + 8], weights[g * 80 + k + 9]);
    // PTX m16n8k16 A fragment order: (row g,k), (row g+8,k),
    // (row g,k+8), (row g+8,k+8). N corresponds to 8 true outputs.
#pragma unroll
    for (int pair = 0; pair < ROW_PAIRS; ++pair) {
      mma(accum[pair], input_pair(tile, group0, pair, k), input_pair(tile, group1, pair, k),
          input_pair(tile, group0, pair, k + 8), input_pair(tile, group1, pair, k + 8), b0, b1);
    }
  }
  const __half b = bias[0];
  const int out_row = by + t / 2;
  const int subcol = 2 * (t % 2);
#pragma unroll
  for (int pair = 0; pair < ROW_PAIRS; ++pair) {
    store_pair(y, batch_base, h, w, out_row + 2 * pair, bx + 4 * group0 + subcol,
               accum[pair][0], accum[pair][1], b);
    store_pair(y, batch_base, h, w, out_row + 2 * pair, bx + 4 * group1 + subcol,
               accum[pair][2], accum[pair][3], b);
  }
}

__global__ void stencil_float(const float* x, const float* weight,
                              const float* bias, float* y, int h, int w) {
  const int col = blockIdx.x * blockDim.x + threadIdx.x;
  const int row = blockIdx.y;
  if (col >= w) return;
  const int64_t base = int64_t(blockIdx.z) * h * w;
  float sum = 0;
#pragma unroll
  for (int ky = 0; ky < 7; ++ky) {
#pragma unroll
    for (int kx = 0; kx < 7; ++kx) {
      int iy = row + ky - 3, ix = col + kx - 3;
      if (iy >= 0 && iy < h && ix >= 0 && ix < w)
        sum = fmaf(x[base + int64_t(iy) * w + ix], weight[ky * 7 + kx], sum);
    }
  }
  y[base + int64_t(row) * w + col] = sum + bias[0];
}
} // namespace

void launch_stencil(const void* x, const void* weight, const void* bias, void* y,
                     int n, int h, int w, bool fp16, cudaStream_t stream) {
  if (fp16) {
    // Bounds are handled in the shared-input load. A single launch includes
    // borders; the template leaves room for separately dispatched interiors.
    stencil_tensorcore<false><<<dim3((w + OUT_W - 1) / OUT_W, (h + OUT_H - 1) / OUT_H, n),
                                WARPS * 32, 0, stream>>>(
        static_cast<const __half*>(x), static_cast<const __half*>(weight),
        static_cast<const __half*>(bias), static_cast<__half*>(y), h, w);
  } else {
    stencil_float<<<dim3((w + 255) / 256, h, n), 256, 0, stream>>>(
        static_cast<const float*>(x), static_cast<const float*>(weight),
        static_cast<const float*>(bias), static_cast<float*>(y), h, w);
  }
}
"""

@functools.lru_cache(maxsize=1)
def _get_extension():
    digest = hashlib.sha256((_CPP_SOURCE + _CUDA_SOURCE).encode()).hexdigest()[:16]
    directory = Path(tempfile.gettempdir()) / ("stencil_shared_mma_" + digest)
    directory.mkdir(parents=True, exist_ok=True)
    # Atomically publish sources; concurrent evaluation processes may import
    # this same source. PyTorch's extension loader serializes the build itself.
    for filename, source in (("binding.cpp", _CPP_SOURCE), ("kernel.cu", _CUDA_SOURCE)):
        target = directory / filename
        if not target.exists() or target.read_text() != source:
            temporary = directory / (filename + "." + str(os.getpid()) + ".tmp")
            temporary.write_text(source)
            temporary.replace(target)
    return load(
        name="stencil_shared_mma_" + digest,
        sources=[str(directory / "binding.cpp"), str(directory / "kernel.cu")],
        build_directory=str(directory),
        extra_cflags=["-O3"],
        extra_cuda_cflags=["-O3", "-lineinfo"],
        verbose=False,
    )


class ModelNew(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1_weight = torch.nn.Parameter(torch.empty(1, 1, 7, 7))
        self.conv1_bias = torch.nn.Parameter(torch.empty(1))
        torch.nn.init.kaiming_uniform_(self.conv1_weight, a=5 ** 0.5)
        fan_in, _ = torch.nn.init._calculate_fan_in_and_fan_out(self.conv1_weight)
        bound = 1 / fan_in ** 0.5 if fan_in > 0 else 0
        torch.nn.init.uniform_(self.conv1_bias, -bound, bound)

    def forward(self, x):
        return _get_extension().forward(x, self.conv1_weight, self.conv1_bias)


def get_inputs():
    return [torch.rand(1, 1, 10240, 10240)]


def get_init_inputs():
    return []
